### ISSUE TITLE
Issues with SSR

### ISSUE THREAD

**Issue by oyeanuj** [ggingell/react-fullscreenable#1]
Hi @ggingell! Firstly, thank you for putting out this work, I know this is brand new! I

I just tried integrating it with my work (on an universal app) and ran into the following issues:

```
error given was: ReferenceError: document is not defined
[1]     at Function.available (node_modules/fullscreen/index.js:10:17)
[1]     at new Fullscreenable (node_modules/react-fullscreenable/lib/index.js:66:56)
```

Typically, these issues go away by just checking that `window` and `document` object are not undefined. In this library, given that most of the utility is around that, I imagine putting a check in the constructor and the render method would mitigate this issue.

Thank you again for the library!

**Comment by ggingell** [comment]
Good call! I don't work with any universal apps at the moment so I forgot about tha code path. I can fix the issue. It might be a week or so before I can publish a fix though, sorry for the delay. 

grantgi




On Tue, Mar 7, 2017 at 10:03 PM -0800, "Anuj" <notifications@github.com> wrote:












Hi @ggingell! Firstly, thank you for putting out this work, I know this is brand new! I


I just tried integrating it with my work (on an universal app) and ran into the following issues:
error given was: ReferenceError: document is not defined
[1]     at Function.available (node_modules/fullscreen/index.js:10:17)
[1]     at new Fullscreenable (node_modules/react-fullscreenable/lib/index.js:66:56)



Typically, these issues go away by just checking that window and document object are not undefined. In this library, given that most of the utility is around that, I imagine putting a check in the constructor and the render method would mitigate this issue.


Thank you again for the library!

**Comment by oyeanuj** [comment]
No worries, and thanks for the quick response! If I was more familiar with the code path and how full screen library works, I'd have attempted a PR myself. Until then, if this makes it easier for you, here is the check that I use in similar situations :

```js
const canUseDOM = !!(
  typeof window !== 'undefined' &&
  window.document &&
  window.document.createElement
);
```

**Comment by ggingell** [comment]
This should now be fixed and published in v2.1.2. I tested it in react-universally project and it functioned as expected. Let me know if you have other issues. Thanks! #08f4432dfbc38d4a29193de7e29920805ddeb7ff
